Feature: make portblock a multistate resource
to be conveniently stacked with with other clones

diff --git a/heartbeat/portblock b/heartbeat/portblock
--- a/heartbeat/portblock
+++ b/heartbeat/portblock
@@ -1,9 +1,10 @@
-#!/bin/sh
+#!/bin/bash
 #
-# portblock: iptables temporary portblocking control 
+# portblock: iptables temporary portblocking control
 #
 # Author:	Sun Jiang Dong (initial version)
 #               Philipp Reisner (per-IP filtering)
+#               Sebastian Baszczyj (nftables code)
 #
 # License:	GNU General Public License (GPL)
 #
@@ -22,7 +23,13 @@
 : ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
 . ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs
 
+if ocf_is_ms; then
+  ocf_log info "Running in multi-state (promotable) mode; 'action' parameter will be ignored."
+fi
+
+
 # Defaults
+OCF_RESKEY_firewall_default="auto"
 OCF_RESKEY_protocol_default=""
 OCF_RESKEY_portno_default=""
 OCF_RESKEY_direction_default="in"
@@ -32,6 +39,7 @@ OCF_RESKEY_reset_local_on_unblock_stop_default="false"
 OCF_RESKEY_tickle_dir_default=""
 OCF_RESKEY_sync_script_default=""
 
+: ${OCF_RESKEY_firewall=${OCF_RESKEY_firewall_default}}
 : ${OCF_RESKEY_protocol=${OCF_RESKEY_protocol_default}}
 : ${OCF_RESKEY_portno=${OCF_RESKEY_portno_default}}
 : ${OCF_RESKEY_direction=${OCF_RESKEY_direction_default}}
@@ -43,13 +51,17 @@ OCF_RESKEY_sync_script_default=""
 #######################################################################
 CMD=`basename $0`
 TICKLETCP=$HA_BIN/tickle_tcp
+TABLE="portblock"
+# Promotion scores
+SCORE_UNPROMOTED=5
+SCORE_PROMOTED=10
 
 usage()
 {
 	cat <<END >&2
-	usage: $CMD {start|stop|status|monitor|meta-data|validate-all}
+	usage: $CMD {start|stop|promote|demote|status|monitor|meta-data|validate-all}
 
-	$CMD is used to temporarily block ports using iptables.
+	$CMD is used to temporarily block ports using iptables or nftables.
 
 	It can be used to blackhole a port before bringing
 	up an IP address, and enable it after a service is started.
@@ -86,8 +98,8 @@ usage()
 	NOTE: iptables is Linux-specific.
 
 	An additional feature in the portblock RA is the tickle ACK function
-	enabled by specifying the tickle_dir parameter. The tickle ACK 
-	triggers the clients to faster reconnect their TCP connections to the 
+	enabled by specifying the tickle_dir parameter. The tickle ACK
+	triggers the clients to faster reconnect their TCP connections to the
 	fail-overed server.
 
 	Please note that this feature is often used for the floating IP fail-
@@ -95,7 +107,7 @@ usage()
 	It doesn't support the cluster alias IP scenario.
 
 	When using the tickle ACK function, in addition to the normal usage
-	of portblock RA, the parameter tickle_dir must be specified in the 
+	of portblock RA, the parameter tickle_dir must be specified in the
 	action=unblock instance of the portblock resources.
 	For example, you may stack resources like below:
 		portblock action=block
@@ -103,18 +115,18 @@ usage()
 		portblock action=unblock tickle_dir=/tickle/state/dir
 
 	If you want to tickle all the TCP connections which connected to _one_
-	floating IP but different ports, no matter how many portblock resources 
-	you have defined, you should enable tickles for _one_ portblock 
+	floating IP but different ports, no matter how many portblock resources
+	you have defined, you should enable tickles for _one_ portblock
 	resource(action=unblock) only.
-	
-	The tickle_dir is a location which stores the established TCP 
-	connections. It can be a shared directory(which is cluster-visible to 
+
+	The tickle_dir is a location which stores the established TCP
+	connections. It can be a shared directory(which is cluster-visible to
 	all nodes) or a local directory.
 	If you use the shared directory, you needn't do any other things.
 	If you use the local directory, you must also specify the sync_script
 	paramater. We recommend you to use csync2 as the sync_script.
-	For example, if you use the local directory /tmp/tickle as tickle_dir, 
-	you could setup the csync2 as the csync2 documentation says and 
+	For example, if you use the local directory /tmp/tickle as tickle_dir,
+	you could setup the csync2 as the csync2 documentation says and
 	configure your /etc/csync2/csync2.cfg like:
 		group ticklegroup {
 		  host node1;
@@ -137,17 +149,25 @@ meta_data() {
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource script for portblock. It is used to temporarily block ports 
-using iptables. In addition, it may allow for faster TCP reconnects
+Resource script for portblock. It is used to block ports
+using iptables or nftables. In addition, it may allow for faster TCP reconnects
 for clients on failover. Use that if there are long lived TCP
 connections to an HA service. This feature is enabled by setting the
 tickle_dir parameter and only in concert with action set to unblock.
 Note that the tickle ACK function is new as of version 3.0.2 and
-hasn't yet seen widespread use.
+hasn't yet seen widespread use. In multi-state mode, the promote action unblocks the ports on the Promoted/Master node and blocks the ports on the Unpromoted/Slaves node(s).
 </longdesc>
 <shortdesc lang="en">Block and unblocks access to TCP and UDP ports</shortdesc>
 
 <parameters>
+<parameter name="firewall" unique="0" required="0">
+<longdesc lang="en">
+Firewall to use, e.g. auto (default), nft, or iptables.
+</longdesc>
+<shortdesc lang="en">Firewall</shortdesc>
+<content type="string" default="${OCF_RESKEY_firewall_default}" />
+</parameter>
+
 <parameter name="protocol" unique="0" required="1">
 <longdesc lang="en">
 The protocol used to be blocked/unblocked.
@@ -202,7 +222,7 @@ The IP address used to be blocked/unblocked.
 
 <parameter name="tickle_dir" unique="0" required="0">
 <longdesc lang="en">
-The shared or local directory (_must_ be absolute path) which 
+The shared or local directory (_must_ be absolute path) which
 stores the established TCP connections.
 </longdesc>
 <shortdesc lang="en">Tickle directory</shortdesc>
@@ -236,6 +256,8 @@ If "both" is used, both the incoming and outgoing ports are blocked.
 <actions>
 <action name="start" timeout="20s" />
 <action name="stop" timeout="20s" />
+<action name="promote" timeout="10s"/>
+<action name="demote" timeout="10s"/>
 <action name="status" depth="0" timeout="10s" interval="10s" />
 <action name="monitor" depth="0" timeout="10s" interval="10s" />
 <action name="meta-data" timeout="5s" />
@@ -273,7 +295,42 @@ active_grep_pat()
   else
     local prot="(udp|17)"
   fi
-  echo "^DROP${w}${prot}${w}--${w}${src}${w}${dst}${w}multiport${w}${4}ports${w}${2}$"
+  if [ "$FIREWALL" = "nft" ]; then
+    local ip
+    [ "$4" = "s" ] && ip=$src || ip=$dst
+    echo "^\s\+ip $4addr ${ip} $1 $4port $2 ct state { established, related, new } drop$"
+  else
+    echo "^DROP${w}${prot}${w}--${w}${src}${w}${dst}${w}multiport${w}${4}ports${w}${2}$"
+  fi
+}
+
+# Update state file atomically
+stateful_update() {
+    local tempfile
+    tempfile=$(mktemp "${OCF_RESKEY_state}.XXXXXX") || { ocf_log err "Failed to create temporary state file"; return $OCF_ERR_GENERIC; }
+    echo "$1" > "$tempfile" || { ocf_log err "Failed to write state file"; rm -f "$tempfile"; return $OCF_ERR_GENERIC; }
+    mv -f "$tempfile" "${OCF_RESKEY_state}" || { ocf_log err "Failed to move state file"; rm -f "$tempfile"; return $OCF_ERR_GENERIC; }
+}
+#stateful_update() {
+#    local tempfile
+#    tempfile="$(mktemp "${OCF_RESKEY_state}.XXXXXX")"
+#    echo "$1" > "$tempfile"
+#    mv -f "$tempfile" "${OCF_RESKEY_state}"
+#}
+
+# Handle state file location
+if [ -z "$OCF_RESKEY_state" ]; then
+    if [ "${OCF_RESKEY_CRM_meta_globally_unique}" = "false" ]; then
+        OCF_RESKEY_state="${HA_VARRUN}/firewall-${OCF_RESOURCE_INSTANCE}.state"
+    else
+        OCF_RESKEY_state="${HA_VARRUN}/firewall-${OCF_RESOURCE_INSTANCE}.state"
+    fi
+fi
+
+
+# Set promotion score
+set_promotion_score() {
+    "${HA_SBIN_DIR}/crm_attribute" --promotion -v "$1" || { ocf_log err "Failed to set promotion score"; return $OCF_ERR_GENERIC;} 
 }
 
 #chain_isactive  {udp|tcp} portno,portno ip chain
@@ -281,7 +338,11 @@ chain_isactive()
 {
   [ "$4" = "OUTPUT" ] && ds="s" || ds="d"
   PAT=$(active_grep_pat "$1" "$2" "$3" "$ds")
-  $IPTABLES $wait -n -L "$4" | grep -qE "$PAT"
+  if [ "$FIREWALL" = "nft" ]; then
+    nft list chain inet $TABLE $4 |& grep -qE "$PAT"
+  else
+    $IPTABLES $wait -n -L "$4" | grep -qE "$PAT"
+  fi
 }
 
 # netstat -tn and ss -Htn, split on whitespace and colon,
@@ -372,8 +433,8 @@ SayInactive()
   ocf_log debug "$CMD DROP rule [$*] is inactive"
 }
 
-#IptablesStatus  {udp|tcp} portno,portno ip {in|out|both} {block|unblock}
-IptablesStatus() {
+#PortStatus  {udp|tcp} portno,portno ip {in|out|both} {block|unblock}
+PortStatus() {
   local rc
   rc=$OCF_ERR_GENERIC
   is_active=0
@@ -421,26 +482,48 @@ IptablesStatus() {
         ;;
     esac
   fi
+#------------multi------------------
+if ocf_is_ms && [ $rc -eq $OCF_SUCCESS ] && [ "$5" = "unblock" ]; then
+        if [ $is_active -eq 0 ]; then
+            ocf_log debug "Portblock monitor succeeded (master)"
+            "${HA_SBIN_DIR}/crm_attribute" --promotion -v $SCORE_PROMOTED || ocf_log warn "Failed to set promotion score"
+            return $OCF_RUNNING_MASTER
+        else
+            "${HA_SBIN_DIR}/crm_attribute" --promotion -v $SCORE_UNPROMOTED || ocf_log warn "Failed to set promotion score"
+        fi
+    elif ocf_is_ms && [ $rc -ne $OCF_SUCCESS ]; then
+        "${HA_SBIN_DIR}/crm_attribute" --promotion -D || ocf_log warn "Failed to clear promotion score"
+    fi
+#-------------multi---------------
+
+
   return $rc
 }
 
-#DoIptables  {-I|-D} {udp|tcp} portno,portno ip chain
-DoIptables()
+#DoPort  {-I|-D} {udp|tcp} portno,portno ip chain
+DoPort()
 {
   op=$1 proto=$2 ports=$3 ip=$4 chain=$5
   active=0; chain_isactive "$proto" "$ports" "$ip" "$chain" && active=1
-  want_active=0; [ "$op" = "-I" ] && want_active=1
+  want_active=0; { [ "$op" = "insert" ] || [ "$op" = "-I" ] && want_active=1; }
   ocf_log debug "active: $active want_active: $want_active"
   if [ $active -eq $want_active ] ; then
     : Chain already in desired state
   else
     [ "$chain" = "OUTPUT" ] && ds="s" || ds="d"
-    $IPTABLES $wait "$op" "$chain" -p "$proto" -${ds} "$ip" -m multiport --${ds}ports "$ports" -j DROP
+    case $FIREWALL in
+      nft)
+        nft $op rule inet $TABLE $chain ip ${ds}addr $ip $proto ${ds}port { $ports } ct state { established, related, new } drop
+        ;;
+      iptables)
+        $IPTABLES $wait "$op" "$chain" -p "$proto" -${ds} "$ip" -m multiport --${ds}ports "$ports" -j DROP
+        ;;
+    esac
   fi
 }
 
-#IptablesBLOCK  {udp|tcp} portno,portno ip {in|out|both} {block|unblock}
-IptablesBLOCK()
+#PortBLOCK  {udp|tcp} portno,portno ip {in|out|both} {block|unblock}
+PortBLOCK()
 {
   local rc_in=0
   local rc_out=0
@@ -456,46 +539,77 @@ IptablesBLOCK()
     then
       : OK -- chain already active
     else
-      if $try_reset ; then
-        $IPTABLES $wait -I OUTPUT -p "$1" -s "$3" -m multiport --sports "$2" -j REJECT --reject-with tcp-reset
-        tickle_local
-      fi
-      $IPTABLES $wait -I INPUT -p "$1" -d "$3" -m multiport --dports "$2" -j DROP
-      rc_in=$?
-      if $try_reset ; then
-        $IPTABLES $wait -D OUTPUT -p "$1" -s "$3" -m multiport --sports "$2" -j REJECT --reject-with tcp-reset
+      if [ "$FIREWALL" = "nft" ]; then
+        if $try_reset ; then
+          nft insert rule inet $TABLE OUTPUT ip saddr $3 $1 sport { $2 } ct state { established, related, new } reject with tcp reset || return $OCF_ERR_GENERIC
+          tickle_local
+        fi
+        nft insert rule inet $TABLE INPUT ip daddr $3 $1 dport { $2 } ct state { established, related, new } drop || return $OCF_ERR_GENERIC
+        rc_in=$?
+        if $try_reset ; then
+          nft delete rule inet $TABLE OUTPUT ip saddr $3 $1 sport { $2 } ct state { established, related, new } reject with tcp reset || return $OCF_ERR_GENERIC
+        fi
+      else
+        if $try_reset ; then
+          $IPTABLES $wait -I OUTPUT -p "$1" -s "$3" -m multiport --sports "$2" -j REJECT --reject-with tcp-reset
+          tickle_local
+        fi
+        $IPTABLES $wait -I INPUT -p "$1" -d "$3" -m multiport --dports "$2" -j DROP
+        rc_in=$?
+        if $try_reset ; then
+          $IPTABLES $wait -D OUTPUT -p "$1" -s "$3" -m multiport --sports "$2" -j REJECT --reject-with tcp-reset
+        fi
       fi
     fi
   fi
   if [ "$4" = "out" ] || [ "$4" = "both" ]; then
-    DoIptables -I "$1" "$2" "$3" OUTPUT
+    if [ "$FIREWALL" = "nft" ]; then
+      DoPort "insert" "$1" "$2" "$3" OUTPUT
+    else
+      DoPort -I "$1" "$2" "$3" OUTPUT
+    fi
     rc_out=$?
   fi
 
   [ $rc_in -gt $rc_out ] && return $rc_in || return $rc_out
 }
 
-#IptablesUNBLOCK  {udp|tcp} portno,portno ip {in|out|both}
-IptablesUNBLOCK()
+#PortUNBLOCK  {udp|tcp} portno,portno ip {in|out|both}
+PortUNBLOCK()
 {
+  local action
+  [ "$FIREWALL" = "nft" ] && action="delete" || action="-D"
   if [ "$4" = "in" ] || [ "$4" = "both" ]; then
-    DoIptables -D "$1" "$2" "$3" INPUT
+    DoPort $action "$1" "$2" "$3" INPUT
   fi
   if [ "$4" = "out" ] || [ "$4" = "both" ]; then
-    DoIptables -D "$1" "$2" "$3" OUTPUT
+    DoPort -D "$1" "$2" "$3" OUTPUT
   fi
 
   return $?
 }
 
-#IptablesStart  {udp|tcp} portno,portno ip {in|out|both} {block|unblock}
-IptablesStart()
+#PortStart  {udp|tcp} portno,portno ip {in|out|both} {block|unblock}
+PortStart()
 {
   ha_pseudo_resource "${OCF_RESOURCE_INSTANCE}" start
+
+  if [ "$FIREWALL" = "nft" ]; then
+            nft add table inet $TABLE 2>/dev/null || { ocf_log err "Failed to create nftables table"; return $OCF_ERR_GENERIC; }
+            nft add chain inet $TABLE INPUT { type filter hook input priority 0\; } 2>/dev/null || { ocf_log err "Failed to create INPUT chain"; return $OCF_ERR_GENERIC; }
+            nft add chain inet $TABLE OUTPUT { type filter hook output priority 0\; } 2>/dev/null || { ocf_log err "Failed to create OUTPUT chain"; return $OCF_ERR_GENERIC; }
+  fi
+#--------------------multi--------------------------------
+if ocf_is_ms; then
+        PortBLOCK "$1" "$2" "$3" "$4" || return $?
+        "${HA_SBIN_DIR}/crm_attribute" --promotion -v $SCORE_UNPROMOTED || ocf_log warn "Failed to set promotion score"
+    else
+
+#-------------------------
   case $5 in
-    block)	IptablesBLOCK "$@";;
+    block)	PortBLOCK "$@";;
     unblock)
-		IptablesUNBLOCK "$@"
+		PortUNBLOCK "$@"
 		rc=$?
 		tickle_remote
 		#ignore run_tickle_tcp exit code!
@@ -503,24 +617,58 @@ IptablesStart()
 		;;
     *)		usage; return 1;
   esac
-
+  fi
   return $?
 }
 
-#IptablesStop  {udp|tcp} portno,portno ip {in|out|both} {block|unblock}
-IptablesStop()
+#PortStop  {udp|tcp} portno,portno ip {in|out|both} {block|unblock}
+PortStop()
 {
   ha_pseudo_resource "${OCF_RESOURCE_INSTANCE}" stop
+#-------------------------------multi-----------
+    local rc
+    if ocf_is_ms; then
+        "${HA_SBIN_DIR}/crm_attribute" --promotion -D || ocf_log warn "Failed to clear promotion score"
+        PortUNBLOCK "$1" "$2" "$3" "$4" || return $?
+    else
+
+#-------------------------
+
+
+
+  if [ "$FIREWALL" = "nft" ]; then
+  	nft delete table inet $TABLE 2>/dev/null && ocf_log warn "NFTables rules removed"
+  fi
+
   case $5 in
-    block)	IptablesUNBLOCK "$@";;
+    block)	PortUNBLOCK "$@";;
     unblock)
 		save_tcp_connections
-		IptablesBLOCK "$@"
+		PortBLOCK "$@"
 		;;
     *)		usage; return 1;;
   esac
-
+  fi
   return $?
+}
+
+PortPromote() {
+    ocf_log info "Promoting firewall"
+    PortUNBLOCK "$protocol" "$portno" "$ip" "$direction" || return $?
+#    PortStop "$@"
+    [ "$action" = "unblock" ] && tickle_remote
+    stateful_update Promoted || return $?
+    set_promotion_score $SCORE_PROMOTED || return $?
+    return $OCF_SUCCESS
+}
+
+PortDemote() {
+    ocf_log info "Demoting firewall"
+    PortBLOCK "$protocol" "$portno" "$ip" "$direction" || return $?
+#    PortStart "$@"
+    stateful_update Demoted || return $?
+    set_promotion_score $SCORE_UNPROMOTED || return $?
+    return $OCF_SUCCESS
 }
 
 #
@@ -532,8 +680,12 @@ CheckPort() {
   echo $1 | $EGREP -qx '[0-9]+(:[0-9]+)?(,[0-9]+(:[0-9]+)?)*'
 }
 
-IptablesValidateAll()
+PortValidateAll()
 {
+  if ocf_is_ms && [ -n "$OCF_RESKEY_action" ]; then
+    ocf_log warn "Your 'action' parameter is ignored in multi-state mode—use promote/demote."
+  fi
+
   check_binary $IPTABLES
   case $protocol in
     tcp|udp)
@@ -558,17 +710,17 @@ IptablesValidateAll()
 	fi
 	if [ ! -d "$OCF_RESKEY_tickle_dir" ]; then
 		ocf_log err "The tickle dir doesn't exist!"
-		exit $OCF_ERR_INSTALLED	  	
+		exit $OCF_ERR_INSTALLED
 	fi
   fi
 
   case $action in
-    block|unblock)	
+    block|unblock)
 	;;
-    *)		
+    *)
 	ocf_log err "Invalid action $action!"
 	exit $OCF_ERR_CONFIGURED
-	;; 
+	;;
   esac
 
   if ocf_is_true $reset_local_on_unblock_stop; then
@@ -582,6 +734,20 @@ IptablesValidateAll()
   fi
 
   return $OCF_SUCCESS
+}
+
+# Detect firewall tool
+detect_firewall_tool() {
+    if have_binary nft; then
+        FIREWALL="nft"
+        ocf_log debug "Detected nftables"
+    elif have_binary iptables; then
+        FIREWALL="iptables"
+        ocf_log debug "Detected iptables"
+    else
+        ocf_log err "No firewall tool available"
+        return $OCF_ERR_CONFIGURED
+    fi
 }
 
 if
@@ -605,17 +771,17 @@ esac
 if [ -z "$OCF_RESKEY_protocol" ]; then
   ocf_log err "Please set OCF_RESKEY_protocol"
   exit $OCF_ERR_CONFIGURED
-fi 
+fi
 
 if [ -z "$OCF_RESKEY_portno" ]; then
   ocf_log err "Please set OCF_RESKEY_portno"
   exit $OCF_ERR_CONFIGURED
-fi 
+fi
 
 if [ -z "$OCF_RESKEY_action" ]; then
   ocf_log err "Please set OCF_RESKEY_action"
   exit $OCF_ERR_CONFIGURED
-fi 
+fi
 
 # iptables v1.4.20+ is required to use -w (wait)
 version=$(iptables -V | grep -oE '[0-9]+[\.0-9]+')
@@ -647,21 +813,41 @@ if [ -n "$OCF_RESKEY_tickle_dir" ] ; then
 	fi
 fi
 
+case $OCF_RESKEY_firewall in
+	auto)
+		detect_firewall_tool
+		;;
+	nft|iptables)
+		FIREWALL="$OCF_RESKEY_firewall"
+		;;
+	*)
+		return $OCF_ERR_CONFIGURED
+		;;
+esac
+
 case $1 in
-  start)	
-			IptablesStart $protocol $portno $ip $direction $action
+  start)
+			PortStart $protocol $portno $ip $direction $action
 			;;
 
-  stop)		
-			IptablesStop $protocol $portno $ip $direction $action
+  stop)
+			PortStop $protocol $portno $ip $direction $action
 			;;
 
-  status|monitor)	
-			IptablesStatus $protocol $portno $ip $direction $action
+  promote)
+			PortPromote $protocol $portno $ip $direction
+			;;
+
+  demote)
+			PortDemote $protocol $portno $ip $direction
+			;;
+
+  status|monitor)
+			PortStatus $protocol $portno $ip $direction $action
 			;;
 
   validate-all)
-			IptablesValidateAll
+			PortValidateAll
 			;;
 
   *)			usage
